- name: variables
  hosts: localhost
  vars:
    course: "linux"
    Trainer: "umamahesh"
    Duration: "120hrs"
  tasks:
  - name: print information 
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from Trainer {{Trainer}},Duration is {{Duration}}."