- name: variables
  hosts: loacalhost
  vars: 
    course: ansible
    Duration: "150hrs"
    Trainer: "shiva"
  tasks:
  - name: print override information 
    vars:
     course: "Devops"
    ansible.builtin.debug:
     msg: "Hi we are learning {{course}} from Trainer {{Trainer}},Duration is "{{duration}}."

  - name: print override information 
    ansible.builtin.debug:
      msg: "Hi we are learning {{course}} from    

