- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "HELLo {{course | default('ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello ,Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"  


- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello ,Good Morning"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"  
