- name: demo on loops
  hosts: web
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - linux
    - shell
    - ansible   

- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.debug:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
    - pstfix
